import "server-only";
import crypto from "node:crypto";

/**
 * Device tokens and pairing codes are both high-entropy random values
 * generated by this server (never user-chosen), so a fast SHA-256 hash is
 * the right tool — unlike a password, there's no low-entropy secret here
 * for a slow adaptive hash (bcrypt/scrypt) to protect against
 * brute-forcing. Only the hash is ever stored; the raw value is returned
 * to the caller exactly once and never persisted.
 */
export function hashSecret(raw: string): string {
  return crypto.createHash("sha256").update(raw).digest("hex");
}

/** A high-entropy device token for the extension — 256 bits, URL-safe. */
export function generateDeviceToken(): string {
  return crypto.randomBytes(32).toString("base64url");
}

// 32-symbol alphabet, no 0/O/1/I — avoids ambiguous characters when a
// person retypes a code by hand. 32 is a power of 2 and divides 256
// evenly, so `randomByte % 32` is exactly uniform (no modulo bias).
const PAIRING_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const PAIRING_CODE_LENGTH = 12;
const PAIRING_CODE_GROUP_SIZE = 4;

/**
 * Human-typeable pairing code, e.g. "K7JP-4M82-QRXT" — displayed once in
 * the web app, entered once into the extension popup. 12 symbols from a
 * 32-symbol alphabet is 12 * log2(32) = 60 bits of entropy (see
 * README.md "Auto Tracking" for the full reasoning behind this length).
 */
export function generatePairingCode(): string {
  const randomBytes = crypto.randomBytes(PAIRING_CODE_LENGTH);
  let code = "";
  for (let i = 0; i < PAIRING_CODE_LENGTH; i++) {
    if (i > 0 && i % PAIRING_CODE_GROUP_SIZE === 0) code += "-";
    code += PAIRING_CODE_ALPHABET[randomBytes[i] % PAIRING_CODE_ALPHABET.length];
  }
  return code;
}

/**
 * Normalizes a pairing code before hashing/lookup — strips formatting
 * (hyphens, whitespace) and uppercases, so a code is recognized whether
 * or not the user reproduces its exact "XXXX-XXXX-XXXX" grouping. Applied
 * symmetrically on both the creation side (before hashing a freshly
 * generated code) and the consumption side (before hashing what the user
 * typed) — the earlier version of this function only trimmed/uppercased,
 * which meant a code retyped without its hyphens would hash differently
 * and silently fail to match; this is now the single source of truth for
 * what actually gets hashed on both sides.
 */
export function normalizePairingCodeInput(raw: string): string {
  return raw.trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
}
