-- Stage 28 fix: the "new Activity on survivor blocks merge-Undo" defense-
-- in-depth check (undo_library_recovery's merge branch) relied on
-- comparing a NEW activity_events row's `created_at` against the recovery
-- row's `created_at` (`ae.created_at > v_recovery.created_at`). Both
-- values are legitimately generated by DIFFERENT clocks: the recovery
-- row's `created_at` comes from the Postgres server's own `now()`, while
-- every real Activity event's `created_at` is generated CLIENT-SIDE (the
-- browser, in `useActivity.ts`'s `logEvent` — `new Date().toISOString()`
-- — persisted as-is, never server-defaulted; the same pattern this
-- migration's own real-database test fixtures used). Any clock skew
-- between a client and the database server — confirmed live during this
-- migration's own validation pass, where the test runner's clock was
-- measurably several seconds behind the Postgres server's clock — can
-- make a genuinely NEW event's client-stamped `created_at` appear EARLIER
-- than the recovery row's server-stamped `created_at`, silently defeating
-- this check. No data was ever at risk (the activity-move logic that
-- follows is entirely id-list-based, keyed on `movedActivityIds`, and
-- never touches an id outside that list regardless of this check's
-- outcome — a missed conflict here could let Undo proceed and revert the
-- survivor's fields despite new Activity existing, but the new Activity
-- row itself is never lost, corrupted, or moved), but the conservative
-- "block Undo on any real change since the merge" guarantee wasn't
-- reliably honored.
--
-- Fix: replace the timestamp comparison with the same clock-independent,
-- exact-set-comparison technique already used for the collection-topology
-- check in 0011 — capture the survivor's OWN pre-merge activity ids
-- (`survivorPreMergeActivityIds`, new) alongside the existing
-- `movedActivityIds`, and at Undo time compare the survivor's CURRENT
-- full activity-id set against the expected union of both. Any
-- difference — in either direction — means real Activity changed since
-- the merge, exactly the same invariant as before, just detected without
-- depending on any clock at all.
--
-- Only these two statements move: one new capture read in
-- merge_library_items (before any mutation, alongside the existing
-- collection/source/activity capture reads), one new field in its
-- recovery payload, and the conflict check itself in
-- undo_library_recovery's merge branch. Every other line of both
-- functions is copied verbatim from 0011. 0011 itself is not edited —
-- it is deployed and immutable.

create or replace function public.merge_library_items(
  p_survivor_id uuid,
  p_duplicate_id uuid,
  p_merged_row jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_first public.library_items%rowtype;
  v_second public.library_items%rowtype;
  v_survivor public.library_items%rowtype;
  v_duplicate public.library_items%rowtype;
  v_now timestamptz := now();
  v_final_metadata jsonb;
  v_numbering_survivor text;
  v_numbering_duplicate text;
  v_season_survivor numeric;
  v_season_duplicate numeric;
  v_episode_survivor numeric;
  v_episode_duplicate numeric;
  v_unit_survivor text;
  v_unit_duplicate text;
  v_catalog_survivor jsonb;
  v_catalog_duplicate jsonb;
  v_survivor_collection_ids jsonb;
  v_duplicate_collection_ids jsonb;
  v_moved_source_ids jsonb;
  v_moved_activity_ids jsonb;
  -- New (0012): the survivor's OWN activity ids at merge time — these
  -- never move, but Undo needs to know them to compute the exact
  -- expected post-merge activity-id set for the survivor.
  v_survivor_activity_ids jsonb;
  v_survivor_after public.library_items%rowtype;
  v_recovery_id uuid;
begin
  if v_uid is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  delete from public.library_recovery_actions where user_id = v_uid and expires_at < v_now;

  if p_survivor_id = p_duplicate_id then
    return jsonb_build_object('status', 'same_item');
  end if;

  if p_survivor_id < p_duplicate_id then
    select * into v_first from public.library_items where id = p_survivor_id and user_id = v_uid for update;
    select * into v_second from public.library_items where id = p_duplicate_id and user_id = v_uid for update;
    v_survivor := v_first;
    v_duplicate := v_second;
  else
    select * into v_first from public.library_items where id = p_duplicate_id and user_id = v_uid for update;
    select * into v_second from public.library_items where id = p_survivor_id and user_id = v_uid for update;
    v_survivor := v_second;
    v_duplicate := v_first;
  end if;

  if v_survivor.id is null or v_duplicate.id is null then
    return jsonb_build_object('status', 'not_found');
  end if;

  if v_survivor.type <> v_duplicate.type then
    return jsonb_build_object('status', 'type_mismatch');
  end if;

  v_catalog_survivor := v_survivor.metadata->'catalogSource';
  v_catalog_duplicate := v_duplicate.metadata->'catalogSource';
  if v_catalog_survivor is not null and v_catalog_duplicate is not null
     and (v_catalog_survivor->>'provider' <> v_catalog_duplicate->>'provider' or v_catalog_survivor->>'externalId' <> v_catalog_duplicate->>'externalId') then
    return jsonb_build_object('status', 'catalog_source_conflict');
  end if;

  v_final_metadata := coalesce(p_merged_row->'metadata', v_survivor.metadata);

  if v_survivor.type in ('anime', 'series') then
    v_numbering_survivor := case when v_survivor.metadata->>'episodeNumbering' = 'seasonal' then 'seasonal'
                                  when v_survivor.metadata ? 'currentEpisode' then 'absolute' else null end;
    v_numbering_duplicate := case when v_duplicate.metadata->>'episodeNumbering' = 'seasonal' then 'seasonal'
                                   when v_duplicate.metadata ? 'currentEpisode' then 'absolute' else null end;

    if v_numbering_survivor is not null and v_numbering_duplicate is not null and v_numbering_survivor <> v_numbering_duplicate then
      return jsonb_build_object('status', 'numbering_mode_conflict');
    end if;

    if coalesce(v_numbering_survivor, v_numbering_duplicate) = 'seasonal' then
      v_season_survivor := coalesce((v_survivor.metadata->>'currentSeason')::numeric, -1);
      v_episode_survivor := coalesce((v_survivor.metadata->>'currentEpisode')::numeric, -1);
      v_season_duplicate := coalesce((v_duplicate.metadata->>'currentSeason')::numeric, -1);
      v_episode_duplicate := coalesce((v_duplicate.metadata->>'currentEpisode')::numeric, -1);

      if v_episode_survivor < 0 and v_episode_duplicate < 0 then
        null;
      elsif v_episode_duplicate < 0
         or v_season_survivor > v_season_duplicate
         or (v_season_survivor = v_season_duplicate and v_episode_survivor >= v_episode_duplicate) then
        v_final_metadata := jsonb_set(v_final_metadata, '{currentSeason}', to_jsonb(v_season_survivor));
        v_final_metadata := jsonb_set(v_final_metadata, '{currentEpisode}', to_jsonb(v_episode_survivor));
        v_final_metadata := jsonb_set(v_final_metadata, '{episodeNumbering}', to_jsonb('seasonal'::text));
      else
        v_final_metadata := jsonb_set(v_final_metadata, '{currentSeason}', to_jsonb(v_season_duplicate));
        v_final_metadata := jsonb_set(v_final_metadata, '{currentEpisode}', to_jsonb(v_episode_duplicate));
        v_final_metadata := jsonb_set(v_final_metadata, '{episodeNumbering}', to_jsonb('seasonal'::text));
      end if;
    elsif coalesce(v_numbering_survivor, v_numbering_duplicate) = 'absolute' then
      v_episode_survivor := coalesce((v_survivor.metadata->>'currentEpisode')::numeric, -1);
      v_episode_duplicate := coalesce((v_duplicate.metadata->>'currentEpisode')::numeric, -1);
      if greatest(v_episode_survivor, v_episode_duplicate) >= 0 then
        v_final_metadata := jsonb_set(v_final_metadata, '{currentEpisode}', to_jsonb(greatest(v_episode_survivor, v_episode_duplicate)));
        v_final_metadata := v_final_metadata - 'currentSeason' - 'episodeNumbering';
      end if;
    end if;
  elsif v_survivor.type = 'manga' then
    v_episode_survivor := coalesce((v_survivor.metadata->>'currentChapter')::numeric, -1);
    v_episode_duplicate := coalesce((v_duplicate.metadata->>'currentChapter')::numeric, -1);
    if greatest(v_episode_survivor, v_episode_duplicate) >= 0 then
      v_final_metadata := jsonb_set(v_final_metadata, '{currentChapter}', to_jsonb(greatest(v_episode_survivor, v_episode_duplicate)));
    end if;
  elsif v_survivor.type = 'novel' then
    v_unit_survivor := coalesce(v_survivor.metadata->>'progressUnit', 'chapter');
    v_unit_duplicate := coalesce(v_duplicate.metadata->>'progressUnit', 'chapter');
    v_episode_survivor := coalesce((v_survivor.metadata->>'progressValue')::numeric, -1);
    v_episode_duplicate := coalesce((v_duplicate.metadata->>'progressValue')::numeric, -1);

    if v_episode_survivor >= 0 and v_episode_duplicate >= 0 and v_unit_survivor <> v_unit_duplicate then
      return jsonb_build_object('status', 'progress_unit_conflict');
    end if;

    if greatest(v_episode_survivor, v_episode_duplicate) >= 0 then
      v_final_metadata := jsonb_set(v_final_metadata, '{progressValue}', to_jsonb(greatest(v_episode_survivor, v_episode_duplicate)));
      v_final_metadata := jsonb_set(
        v_final_metadata, '{progressUnit}',
        to_jsonb(case when v_episode_survivor >= 0 then v_unit_survivor else v_unit_duplicate end)
      );
    end if;
  elsif v_survivor.type = 'game' then
    v_episode_survivor := coalesce((v_survivor.metadata->>'playtimeHours')::numeric, -1);
    v_episode_duplicate := coalesce((v_duplicate.metadata->>'playtimeHours')::numeric, -1);
    if greatest(v_episode_survivor, v_episode_duplicate) >= 0 then
      v_final_metadata := jsonb_set(v_final_metadata, '{playtimeHours}', to_jsonb(greatest(v_episode_survivor, v_episode_duplicate)));
    end if;
  end if;

  if v_survivor.metadata ? 'anilistSync' then
    v_final_metadata := jsonb_set(v_final_metadata, '{anilistSync}', v_survivor.metadata->'anilistSync');
  elsif v_duplicate.metadata ? 'anilistSync' then
    v_final_metadata := jsonb_set(v_final_metadata, '{anilistSync}', v_duplicate.metadata->'anilistSync');
  end if;

  select coalesce(jsonb_agg(collection_id), '[]'::jsonb) into v_survivor_collection_ids
  from public.collection_items where item_id = p_survivor_id and user_id = v_uid;
  select coalesce(jsonb_agg(collection_id), '[]'::jsonb) into v_duplicate_collection_ids
  from public.collection_items where item_id = p_duplicate_id and user_id = v_uid;
  select coalesce(jsonb_agg(id), '[]'::jsonb) into v_moved_source_ids
  from public.tracking_sources where library_item_id = p_duplicate_id and user_id = v_uid;
  select coalesce(jsonb_agg(id), '[]'::jsonb) into v_moved_activity_ids
  from public.activity_events where item_id = p_duplicate_id and user_id = v_uid;
  -- New (0012): survivor's own pre-merge activity ids — never moves, but
  -- needed at Undo time to compute the exact expected post-merge set.
  select coalesce(jsonb_agg(id), '[]'::jsonb) into v_survivor_activity_ids
  from public.activity_events where item_id = p_survivor_id and user_id = v_uid;

  update public.library_items
  set
    title = coalesce(p_merged_row->>'title', v_survivor.title),
    description = coalesce(p_merged_row->>'description', v_survivor.description),
    category = coalesce(p_merged_row->>'category', v_survivor.category),
    tags = coalesce((select array_agg(x) from jsonb_array_elements_text(p_merged_row->'tags') x), v_survivor.tags),
    favorite = coalesce((p_merged_row->>'favorite')::boolean, v_survivor.favorite),
    image_url = p_merged_row->>'image_url',
    source_url = p_merged_row->>'source_url',
    status = coalesce(p_merged_row->>'status', v_survivor.status),
    rating = (p_merged_row->>'rating')::numeric,
    metadata = v_final_metadata,
    updated_at = v_now
  where id = p_survivor_id and user_id = v_uid;

  select * into v_survivor_after from public.library_items where id = p_survivor_id and user_id = v_uid;

  v_recovery_id := gen_random_uuid();
  insert into public.library_recovery_actions (id, user_id, action_type, payload, created_at, expires_at)
  values (
    v_recovery_id,
    v_uid,
    'merge_items',
    jsonb_build_object(
      'survivorId', p_survivor_id,
      'duplicateId', p_duplicate_id,
      'survivorPreMerge', to_jsonb(v_survivor),
      'duplicatePreMerge', to_jsonb(v_duplicate),
      'survivorPostMergeExpected', to_jsonb(v_survivor_after),
      'survivorPreMergeCollectionIds', v_survivor_collection_ids,
      'duplicatePreMergeCollectionIds', v_duplicate_collection_ids,
      'movedSourceIds', v_moved_source_ids,
      'movedActivityIds', v_moved_activity_ids,
      'survivorPreMergeActivityIds', v_survivor_activity_ids
    ),
    v_now,
    v_now + interval '15 minutes'
  );

  update public.tracking_sources
  set library_item_id = p_survivor_id, updated_at = v_now
  where library_item_id = p_duplicate_id and user_id = v_uid;

  insert into public.collection_items (collection_id, item_id, user_id, added_at)
  select ci.collection_id, p_survivor_id, v_uid, ci.added_at
  from public.collection_items ci
  where ci.item_id = p_duplicate_id and ci.user_id = v_uid
  on conflict (collection_id, item_id) do nothing;

  delete from public.collection_items where item_id = p_duplicate_id and user_id = v_uid;

  with moved as (
    delete from public.activity_events
    where item_id = p_duplicate_id and user_id = v_uid
    returning id, user_id, type, data, created_at
  )
  insert into public.activity_events (id, user_id, item_id, type, data, created_at)
  select id, user_id, p_survivor_id, type, data, created_at from moved;

  delete from public.library_items where id = p_duplicate_id and user_id = v_uid;

  return jsonb_build_object('status', 'merged', 'survivorId', p_survivor_id, 'recoveryId', v_recovery_id);
end;
$$;

revoke all on function public.merge_library_items(uuid, uuid, jsonb) from public;
grant execute on function public.merge_library_items(uuid, uuid, jsonb) to authenticated;

create or replace function public.undo_library_recovery(
  p_recovery_id uuid
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_now timestamptz := now();
  v_recovery public.library_recovery_actions%rowtype;
  v_existing_id uuid;
  v_missing_collection boolean;
  v_conflicted_source boolean;
  v_item jsonb;
  v_collection_ids jsonb;
  v_activity_events jsonb;
  v_source_ids jsonb;
  v_survivor_id uuid;
  v_duplicate_id uuid;
  v_survivor_pre jsonb;
  v_duplicate_pre jsonb;
  v_survivor_post_expected jsonb;
  v_survivor_collection_ids jsonb;
  v_duplicate_collection_ids jsonb;
  v_moved_source_ids jsonb;
  v_moved_activity_ids jsonb;
  -- New (0012): replaces v_new_unrelated_activity's timestamp comparison.
  v_survivor_activity_ids jsonb;
  v_current_survivor public.library_items%rowtype;
  v_topology_mismatch boolean;
  v_activity_topology_mismatch boolean;
begin
  if v_uid is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  perform pg_advisory_xact_lock(hashtext(p_recovery_id::text));

  select * into v_recovery from public.library_recovery_actions where id = p_recovery_id and user_id = v_uid;
  if v_recovery.id is null then
    return jsonb_build_object('status', 'not_found');
  end if;

  if v_recovery.expires_at < v_now then
    delete from public.library_recovery_actions where id = p_recovery_id;
    return jsonb_build_object('status', 'expired');
  end if;

  -- ============================================================
  -- delete_item
  -- ============================================================
  if v_recovery.action_type = 'delete_item' then
    v_item := v_recovery.payload->'item';
    v_collection_ids := coalesce(v_recovery.payload->'collectionIds', '[]'::jsonb);
    v_activity_events := coalesce(v_recovery.payload->'activityEvents', '[]'::jsonb);
    v_source_ids := coalesce(v_recovery.payload->'sourceIds', '[]'::jsonb);

    select id into v_existing_id from public.library_items where id = (v_item->>'id')::uuid;
    if v_existing_id is not null then
      return jsonb_build_object('status', 'recovery_conflict', 'reason', 'id_in_use');
    end if;

    select exists (
      select 1 from jsonb_array_elements_text(v_collection_ids) cid
      where not exists (select 1 from public.collections c where c.id = cid::uuid and c.user_id = v_uid)
    ) into v_missing_collection;
    if v_missing_collection then
      return jsonb_build_object('status', 'recovery_conflict', 'reason', 'collection_missing');
    end if;

    select exists (
      select 1 from jsonb_array_elements_text(v_source_ids) sid
      where not exists (select 1 from public.tracking_sources ts where ts.id = sid::uuid and ts.user_id = v_uid and ts.library_item_id is null)
    ) into v_conflicted_source;
    if v_conflicted_source then
      return jsonb_build_object('status', 'recovery_conflict', 'reason', 'source_claimed_elsewhere');
    end if;

    insert into public.library_items (id, user_id, type, title, description, category, tags, favorite, image_url, source_url, url, status, rating, metadata, created_at, updated_at)
    values (
      (v_item->>'id')::uuid,
      v_uid,
      v_item->>'type',
      v_item->>'title',
      v_item->>'description',
      v_item->>'category',
      coalesce((select array_agg(x) from jsonb_array_elements_text(v_item->'tags') x), '{}'),
      (v_item->>'favorite')::boolean,
      v_item->>'image_url',
      v_item->>'source_url',
      v_item->>'url',
      v_item->>'status',
      (v_item->>'rating')::numeric,
      coalesce(v_item->'metadata', '{}'::jsonb),
      (v_item->>'created_at')::timestamptz,
      case when v_item->>'updated_at' is null then null else (v_item->>'updated_at')::timestamptz end
    );

    insert into public.collection_items (collection_id, item_id, user_id, added_at)
    select cid::uuid, (v_item->>'id')::uuid, v_uid, v_now
    from jsonb_array_elements_text(v_collection_ids) cid;

    insert into public.activity_events (id, user_id, item_id, type, data, created_at)
    select (e->>'id')::uuid, v_uid, (v_item->>'id')::uuid, e->>'type', coalesce(e->'data', '{}'::jsonb), (e->>'created_at')::timestamptz
    from jsonb_array_elements(v_activity_events) e;

    update public.tracking_sources
    set library_item_id = (v_item->>'id')::uuid, updated_at = v_now
    where user_id = v_uid
      and library_item_id is null
      and id in (select sid::uuid from jsonb_array_elements_text(v_source_ids) sid);

    delete from public.library_recovery_actions where id = p_recovery_id;

    return jsonb_build_object('status', 'recovered', 'actionType', 'delete_item', 'itemId', (v_item->>'id')::uuid);
  end if;

  -- ============================================================
  -- merge_items
  -- ============================================================
  if v_recovery.action_type = 'merge_items' then
    v_survivor_id := (v_recovery.payload->>'survivorId')::uuid;
    v_duplicate_id := (v_recovery.payload->>'duplicateId')::uuid;
    v_survivor_pre := v_recovery.payload->'survivorPreMerge';
    v_duplicate_pre := v_recovery.payload->'duplicatePreMerge';
    v_survivor_post_expected := v_recovery.payload->'survivorPostMergeExpected';
    v_survivor_collection_ids := coalesce(v_recovery.payload->'survivorPreMergeCollectionIds', '[]'::jsonb);
    v_duplicate_collection_ids := coalesce(v_recovery.payload->'duplicatePreMergeCollectionIds', '[]'::jsonb);
    v_moved_source_ids := coalesce(v_recovery.payload->'movedSourceIds', '[]'::jsonb);
    v_moved_activity_ids := coalesce(v_recovery.payload->'movedActivityIds', '[]'::jsonb);
    v_survivor_activity_ids := coalesce(v_recovery.payload->'survivorPreMergeActivityIds', '[]'::jsonb);

    select * into v_current_survivor from public.library_items where id = v_survivor_id and user_id = v_uid for update;
    if v_current_survivor.id is null then
      return jsonb_build_object('status', 'recovery_conflict', 'reason', 'survivor_missing');
    end if;

    select id into v_existing_id from public.library_items where id = v_duplicate_id;
    if v_existing_id is not null then
      return jsonb_build_object('status', 'recovery_conflict', 'reason', 'id_in_use');
    end if;

    if to_jsonb(v_current_survivor) is distinct from v_survivor_post_expected then
      return jsonb_build_object('status', 'recovery_conflict', 'reason', 'survivor_changed');
    end if;

    -- Fix (0012): clock-independent replacement for the old
    -- created_at-comparison defense-in-depth check. The survivor's
    -- CURRENT full activity-id set must exactly equal the expected
    -- post-merge union (its own pre-merge ids, which never moved, plus
    -- the ids moved in from the duplicate) — any id present now that
    -- isn't in that union (new Activity since the merge) or missing from
    -- it (an original event somehow gone) is real evidence of a change,
    -- detected without depending on any clock anywhere.
    select exists (
      select 1 from (
        (
          select id from public.activity_events
          where item_id = v_survivor_id and user_id = v_uid
          except
          select cid::uuid from jsonb_array_elements_text(v_survivor_activity_ids || v_moved_activity_ids) cid
        )
        union all
        (
          select cid::uuid from jsonb_array_elements_text(v_survivor_activity_ids || v_moved_activity_ids) cid
          except
          select id from public.activity_events
          where item_id = v_survivor_id and user_id = v_uid
        )
      ) as diff
    ) into v_activity_topology_mismatch;
    if v_activity_topology_mismatch then
      return jsonb_build_object('status', 'recovery_conflict', 'reason', 'survivor_changed');
    end if;

    select exists (
      select 1 from jsonb_array_elements_text(v_moved_source_ids) sid
      where not exists (select 1 from public.tracking_sources ts where ts.id = sid::uuid and ts.user_id = v_uid and ts.library_item_id = v_survivor_id)
    ) into v_conflicted_source;
    if v_conflicted_source then
      return jsonb_build_object('status', 'recovery_conflict', 'reason', 'source_claimed_elsewhere');
    end if;

    select exists (
      select 1 from jsonb_array_elements_text(v_survivor_collection_ids || v_duplicate_collection_ids) cid
      where not exists (select 1 from public.collections c where c.id = cid::uuid and c.user_id = v_uid)
    ) into v_missing_collection;
    if v_missing_collection then
      return jsonb_build_object('status', 'recovery_conflict', 'reason', 'collection_missing');
    end if;

    select exists (
      select 1 from (
        (
          select collection_id from public.collection_items
          where item_id = v_survivor_id and user_id = v_uid
          except
          select cid::uuid from jsonb_array_elements_text(v_survivor_collection_ids || v_duplicate_collection_ids) cid
        )
        union all
        (
          select cid::uuid from jsonb_array_elements_text(v_survivor_collection_ids || v_duplicate_collection_ids) cid
          except
          select collection_id from public.collection_items
          where item_id = v_survivor_id and user_id = v_uid
        )
      ) as diff
    ) into v_topology_mismatch;
    if v_topology_mismatch then
      return jsonb_build_object('status', 'recovery_conflict', 'reason', 'collections_changed');
    end if;

    insert into public.library_items (id, user_id, type, title, description, category, tags, favorite, image_url, source_url, url, status, rating, metadata, created_at, updated_at)
    values (
      (v_duplicate_pre->>'id')::uuid,
      v_uid,
      v_duplicate_pre->>'type',
      v_duplicate_pre->>'title',
      v_duplicate_pre->>'description',
      v_duplicate_pre->>'category',
      coalesce((select array_agg(x) from jsonb_array_elements_text(v_duplicate_pre->'tags') x), '{}'),
      (v_duplicate_pre->>'favorite')::boolean,
      v_duplicate_pre->>'image_url',
      v_duplicate_pre->>'source_url',
      v_duplicate_pre->>'url',
      v_duplicate_pre->>'status',
      (v_duplicate_pre->>'rating')::numeric,
      coalesce(v_duplicate_pre->'metadata', '{}'::jsonb),
      (v_duplicate_pre->>'created_at')::timestamptz,
      case when v_duplicate_pre->>'updated_at' is null then null else (v_duplicate_pre->>'updated_at')::timestamptz end
    );

    update public.library_items
    set
      title = v_survivor_pre->>'title',
      description = v_survivor_pre->>'description',
      category = v_survivor_pre->>'category',
      tags = coalesce((select array_agg(x) from jsonb_array_elements_text(v_survivor_pre->'tags') x), '{}'),
      favorite = (v_survivor_pre->>'favorite')::boolean,
      image_url = v_survivor_pre->>'image_url',
      source_url = v_survivor_pre->>'source_url',
      status = v_survivor_pre->>'status',
      rating = (v_survivor_pre->>'rating')::numeric,
      metadata = coalesce(v_survivor_pre->'metadata', '{}'::jsonb),
      updated_at = case when v_survivor_pre->>'updated_at' is null then null else (v_survivor_pre->>'updated_at')::timestamptz end
    where id = v_survivor_id and user_id = v_uid;

    delete from public.collection_items where item_id = v_survivor_id and user_id = v_uid;
    insert into public.collection_items (collection_id, item_id, user_id, added_at)
    select cid::uuid, v_survivor_id, v_uid, v_now from jsonb_array_elements_text(v_survivor_collection_ids) cid;
    insert into public.collection_items (collection_id, item_id, user_id, added_at)
    select cid::uuid, v_duplicate_id, v_uid, v_now from jsonb_array_elements_text(v_duplicate_collection_ids) cid;

    with moved as (
      delete from public.activity_events
      where user_id = v_uid
        and item_id = v_survivor_id
        and id in (select x::uuid from jsonb_array_elements_text(v_moved_activity_ids) x)
      returning id, user_id, type, data, created_at
    )
    insert into public.activity_events (id, user_id, item_id, type, data, created_at)
    select id, user_id, v_duplicate_id, type, data, created_at from moved;

    update public.tracking_sources
    set library_item_id = v_duplicate_id, updated_at = v_now
    where user_id = v_uid
      and library_item_id = v_survivor_id
      and id in (select x::uuid from jsonb_array_elements_text(v_moved_source_ids) x);

    delete from public.library_recovery_actions where id = p_recovery_id;

    return jsonb_build_object('status', 'recovered', 'actionType', 'merge_items', 'survivorId', v_survivor_id, 'duplicateId', v_duplicate_id);
  end if;

  return jsonb_build_object('status', 'invalid_action');
end;
$$;

revoke all on function public.undo_library_recovery(uuid) from public;
grant execute on function public.undo_library_recovery(uuid) to authenticated;
